from __future__ import annotations

from tasks.translate import (
    EntryStatus,
    FileKind,
    TSEntryAdapter,
    ResxEntryAdapter,
    StringsEntryAdapter,
    UnifiedEntry,
    apply_translation_to_entry,
    build_entry_source_text,
    build_output_path,
    detect_file_kind,
    get_entry_prompt_context_and_note,
    load_po,
    load_resx,
    load_strings,
    load_ts,
    load_txt,
    select_work_items,
)

__all__ = [
    "EntryStatus",
    "FileKind",
    "TSEntryAdapter",
    "ResxEntryAdapter",
    "StringsEntryAdapter",
    "UnifiedEntry",
    "apply_translation_to_entry",
    "build_entry_source_text",
    "build_output_path",
    "detect_file_kind",
    "get_entry_prompt_context_and_note",
    "load_po",
    "load_resx",
    "load_strings",
    "load_ts",
    "load_txt",
    "select_work_items",
]
